name: matching-docs
channels:
    - defaults
dependencies:
    - matplotlib>=3
    - numpy>=1.16
    - pandas>=0.24
    - ipython>=7.6
    - python>=3.6
    - pip>=19
    - pip:
        - matching
        - nbsphinx
        - sphinx_rtd_theme
        - sphinxcontrib-bibtex
